name 'chef-nginx-gcp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-nginx-gcp'
long_description 'Installs/Configures chef-nginx-gcp'
version '0.1.0'
